kind: DatadogAgent
apiVersion: datadoghq.com/v2alpha1
metadata:
  name: datadog
spec:
  global:
    # Update site if using a Datadog organization outside of US1
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      #Uncommment if using spec.features.externalMetricsServer.enabled: true
      ##appSecret:
      ####secretName: datadog-secret
      ####keyName: app-key
    kubelet:
      tlsVerify: false
  features:
    apm:
      enabled: true
      hostPortConfig:
        enabled: true
        hostPort: 8126
      unixDomainSocketConfig:
        enabled: true
    dogstatsd:
      hostPortConfig:
        enabled: true
        hostPort: 8125
    logCollection:
      enabled: true
      containerCollectAll: true
    liveProcessCollection:
      enabled: true
    liveContainerCollection:
      enabled: true
    kubeStateMetricsCore:
      enabled: true
    cspm:
      enabled: false
    cws:
      enabled: false
    npm:
      enabled: true
    admissionController:
      enabled: true
      mutateUnlabelled: false
    externalMetricsServer:
      enabled: false
      useDatadogMetrics: false
      port: 8443
  override:
    clusterAgent:
      image:
        name: gcr.io/datadoghq/cluster-agent:latest
      extraConfd:
        configDataMap:
          kube_apiserver_metrics.yaml: |-
            cluster_check: true
            init_config:
            instances:
              - prometheus_url: https://kubernetes.default/metrics
                ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                bearer_token_auth: true
          kube_controller_manager.yaml: |-
            cluster_check: true
            init_config:
            instances:
              - prometheus_url: https://kubernetes.default/metrics
                ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                bearer_token_auth: true
    nodeAgent:
      image:
        name: gcr.io/datadoghq/agent:latest