# Values for datadog-operator.
apiKeyExistingSecret:  datadog-keys
appKeyExistingSecret:  datadog-keys

## Set to 'datadoghq.com' to send data to the US1 site (default).
## Set to 'datadoghq.eu' to send data to the EU site.
## Set to 'us3.datadoghq.com' to send data to the US3 site.
## Set to 'us5.datadoghq.com' to send data to the US5 site.
## Set to 'ddog-gov.com' to send data to the US1-FED site.
## Set to 'ap1.datadoghq.com' to send data to the AP1 site.
site:  # datadoghq.com

datadogMonitor:
  # datadogMonitor.enabled -- Enables the Datadog Monitor controller
  enabled: true