datadog:
  apiKeyExistingSecret: datadog-keys
  # Uncomment site: if using a Datadog Organization outside of US1
  # site: ddog-gov.com
  inventories_configuration_enabled: true
  apm:
    portEnabled: true
  logs:
    enabled: true
    containerCollectAll: true
    autoMultiLineDetection: true
  processAgent:
    processCollection: true
  dogstatsd:
    useHostPort: true
  kubeStateMetricsCore:
    enabled: true
  kubeStateMetricsEnabled: false
  kubelet:
    tlsVerify: false
  networkMonitoring:
    enabled: true
clusterAgent:
  admissionController:
    enabled: true
    # clusterAgent.admissionController.mutateUnlabelled -- Enable injecting config without having the pod label 'admission.datadoghq.com/enabled="true". See -- https://docs.datadoghq.com/containers/cluster_agent/admission_controller/?tab=helm'
    mutateUnlabelled: true
  confd:
    kube_apiserver_metrics.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://kubernetes.default/metrics
          ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_auth: true
    kube_controller_manager.yaml: |-
      cluster_check: true
      init_config:
      instances:
        - prometheus_url: https://kubernetes.default/metrics
          ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          bearer_token_auth: true
agents:
  useConfigMap: true
  customAgentConfig:
    kubelet_tls_verify: false
    ### Use below if running DDOG Agent < 7.39
    vector:
      logs:
        enabled: true
        url: "http://vector.vector:8282"
      metrics:
        enabled: true
        url: "http://vector.vector:8282"
      traces:
        enabled: true
        url: "http://vector.vector:8282"