targetSystem: "windows"
existingClusterAgent:
  join: true
  serviceName: "datadog-cluster-agent" # from the first Datadog Helm chart
  tokenSecretName: "datadog-cluster-agent" # from the first Datadog Helm chart
  clusterchecksEnabled: false # stops DCA from schedule cluster checks on any windows agents
# Disable datadogMetrics deployment since it should have been already deployed with the first chart.
datadog-crds:
  crds:
    datadogMetrics: false
# Disable kube-state-metrics deployment
datadog:
  kubeStateMetricsEnabled: false
  apiKeyExistingSecret: datadog-keys
  # Uncomment site: if using a Datadog Organization outside of US1
  # site: ddog-gov.com
  env:
    - name: DD_EC2_PREFER_IMDSV2
      value: "true"
    - name: DD_INVENTORIES_CONFIGURATION_ENABLED
      value: "true"
  dogstatsd:
    useSocketVolume: false
  kubeStateMetricsCore:
    enabled: false 
  processAgent:
    enabled: true # enables orchestrator data collection
    processCollection: false # not supported on Windows Nodes/Containers
  apm:
    socketEnabled: false # not supported on Windows Nodes/Containers
    portEnabled: true
  logs:
    enabled: true
    containerCollectAll: true
    autoMultiLineDetection: true
agents:
  tolerations:
  - operator: Exists
  forceLocalServiceEnabled: true