apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootapp
  labels:
      app: springbootapp
      tags.datadoghq.com/env: "training"
      tags.datadoghq.com/service: "SpringBoot"
      tags.datadoghq.com/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootapp
  template:
    metadata:
      labels:
        app: springbootapp
        tags.datadoghq.com/env: "training"
        tags.datadoghq.com/service: "SpringBoot"
        tags.datadoghq.com/version: "1.0"
      # annotations:
      #   admission.datadoghq.com/java-lib.version: "v1.10.0"
    spec:
      containers:
      - name: springbootapp
        image: ethomatos/sample_springboot:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_AGENT_PORT
          value: '8126'
        - name: DD_JMXFETCH_ENABLED
          value: "true"
        - name: DD_STATSD_PORT
          value: '8125'
        - name: DD_JMXFETCH_STATSD_PORT
          value: '8125'
        - name: DD_LOGS_INJECTION
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: springbootapp
spec:
  selector:
    app: springbootapp
  ports:
  - name: http
    protocol: TCP
    port: 8080
  type: LoadBalancer